Create Login feature
code4romania/expert-consultation-backend pull request #22
Opened 2021-08-02 09:34 UTC by lupudeni

### What does it fix?

Closes https://github.com/code4romania/expert-consultation-backend/issues/21

Create Login feature with jwt
### How has it been tested?

Manual testing:

- Use Postman (or other tool for the REST api)
- create request: POST on _http://localhost:8080/api/auth/login_
- For successful login use the following request body (the response body should be composed of an  _"accessTocken"_ and a _"tockenType"_) :
  {
    "username": "test@test.com",
    "password": "test",
    "authorities" : []
}

- For Unauthorized use the following request body (response should be http 401):
 {
    "username": "unknown@test.com",
    "password": "test",
    "authorities" : []
}

2021-08-02 13:37 UTC, georgebejan requested changes

2021-08-02 13:37 UTC, georgebejan commented on src/main/java/ro/code4/expertconsultation/authentication/controller/AuthenticationController.java
> +    public ResponseEntity<JwtAuthenticationResponse> login(@RequestBody final CurrentUser currentUser) {
Here it doesn't really make sense to use the `CurrentUser` as request body. Since this can evolve in time and we need only username and password here. Better create a new class for the login request with only the username and password

2021-08-02 13:37 UTC, georgebejan commented on src/main/java/ro/code4/expertconsultation/authentication/service/impl/AuthenticationServiceImpl.java
> +//    private UserService userService;
remove these if no longer used

2021-08-02 13:37 UTC, georgebejan commented on src/main/java/ro/code4/expertconsultation/authentication/service/impl/CustomUserDetailsService.java
> +public class CustomUserDetailsService implements UserDetailsService {
`UserService` already extends `UserDetailsService`. If we are keeping the implementation here, please remove it from `UserService`

2021-08-02 13:37 UTC, georgebejan commented on etc/docker/docker-compose.yml
> +#  expert-backend-prod:
revert this and use `docker-compose-dev` for local development

2021-08-02 15:23 UTC, lupudeni commented on src/main/java/ro/code4/expertconsultation/authentication/controller/AuthenticationController.java
> +    public ResponseEntity<JwtAuthenticationResponse> login(@RequestBody final CurrentUser currentUser) {
done

2021-08-02 15:24 UTC, lupudeni commented on src/main/java/ro/code4/expertconsultation/authentication/service/impl/AuthenticationServiceImpl.java
> +//    private UserService userService;
done

2021-08-02 15:24 UTC, lupudeni commented on src/main/java/ro/code4/expertconsultation/authentication/service/impl/CustomUserDetailsService.java
> +public class CustomUserDetailsService implements UserDetailsService {
done

2021-08-02 15:24 UTC, lupudeni commented on etc/docker/docker-compose.yml
> +#  expert-backend-prod:
done

2021-08-13 04:52 UTC, georgebejan requested changes

2021-08-13 04:52 UTC, georgebejan commented on etc/docker/docker-compose.yml
> -  expert-backend-prod:
please revert this

2021-08-13 08:37 UTC, lupudeni commented on etc/docker/docker-compose.yml
> -  expert-backend-prod:
done

2021-08-27 07:58 UTC, tododeni commented on etc/docker/docker-compose.yml
> +#  expert-backend-prod:
copied from master and replaced

2021-08-27 08:47 UTC, georgebejan approved these changes

2021-08-27 08:48 UTC, merged